scalarHubRockstarHire/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :feedbacks, only: [:create]
    end
  end
resources :image_links
root 'image_links#index'

get "/search_images", to: "image_links#search", as: :search_image_links

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
# Can be used by load balancers and uptime monitors to verify that the app is live.
get "up" => "rails/health#show", as: :rails_health_check

# Defines the root path route ("/")
# root "posts#index"
#root 'home#index'
 #get 'feedbacks/create'
end

scalarHubRockstarHire/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

scalarHubRockstarHire/app/models/feedback.rb
class Feedback < ApplicationRecord
    validates :name, presence: true
   
end

scalarHubRockstarHire/app/models/image_link.rb
class ImageLink < ApplicationRecord
    acts_as_taggable_on :tags


    validates :tag_list, presence: { message: "provide please." }
    validates :url, presence: { message: "provide please." }
    validates :url, format: { with: URI::DEFAULT_PARSER.make_regexp, message: "is not valid" }
end
  

scalarHubRockstarHire/app/controllers/api/v1/feedbacks_controller.rb
class Api::V1::FeedbacksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.save
      render json: { message: 'Feedback submitted successfully' }, status: :created
    else
      render json: { errors: @feedback.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :email, :comment)
  end
end

# app/controllers/api/v1/feedbacks_controller.rb

class Api::V1::FeedbacksController < ApplicationController
  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.save
      render json: { message: 'Feedback submitted successfully' }, status: :ok
    else
      render json: { errors: @feedback.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :email, :comment)
  end
end

scalarHubRockstarHire/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

scalarHubRockstarHire/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

scalarHubRockstarHire/app/controllers/image_links_controller.rb
class ImageLinksController < ApplicationController
    before_action :set_image_link, only: %i[ show edit update destroy ]
  
    # GET /image_links or /image_links.json
    def index
      @image_links = ImageLink.order(created_at: :desc)
    end
  
    
    # GET /image_links/1 or /image_links/1.json
    def show
      @image_link = ImageLink.find(params[:id])
    end
  
    # GET /image_links/new
    def new
      @image_link = ImageLink.new
    end
  
    # GET /image_links/1/edit
    def edit
    end
  
    # POST /image_links or /image_links.json
    def create
      @image_link = ImageLink.new(image_link_params)
  
     
      respond_to do |format|
        if @image_link.save
          format.html { redirect_to image_link_url(@image_link), notice: "Image link was successfully created." }
          format.json { render :show, status: :created, location: @image_link }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @image_link.errors, status: :unprocessable_entity }
        end
      end
    end
    
  
    # PATCH/PUT /image_links/1 or /image_links/1.json
    def update
      respond_to do |format|
        if @image_link.update(image_link_params)
          format.html { redirect_to image_link_url(@image_link), notice: "Image link was successfully updated." }
          format.json { render :show, status: :ok, location: @image_link }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @image_link.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /image_links/1 or /image_links/1.json
    def destroy
      @image_link.destroy!
  
      respond_to do |format|
        format.html { redirect_to image_links_url, notice: "Image link was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    
    
   def search
    @tag = params[:tag]
    @search_results = ImageLink.tagged_with(@tag) if @tag.present?
  
    if @search_results.blank?
      raise ActiveRecord::RecordNotFound, "No ImageLink records found with tag: '#{@tag}'"
    end
  end
  
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_image_link
        @image_link = ImageLink.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def image_link_params
        params.require(:image_link).permit(:url, :tag_list)
      end
    end
  
      

scalarHubRockstarHire/app/helpers/api/v1/feedbacks_helper.rb
module Api::V1::FeedbacksHelper
end

scalarHubRockstarHire/app/helpers/application_helper.rb
module ApplicationHelper
end

scalarHubRockstarHire/app/helpers/home_helper.rb
module HomeHelper
end

scalarHubRockstarHire/app/views/home/_footer.html.erb
<div id='welcome'>
</div>

scalarHubRockstarHire/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-info-subtle" style="position: sticky; top: 0; background-color: info-subtle; z-index: 100;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "New image", new_image_link_path, class: "nav-link active" %>
          </li>
        </ul>
      </ul>

      <%= form_tag(search_image_links_path, method: :get, class: "d-flex") do %>
        <input class="form-control me-2" type="search" name="tag" placeholder="Search" aria-label="Search" value="<%= params[:tag] %>">
        <button class="btn btn-outline-success" type="submit">Search</button>
      <% end %>
    </div>
  </div>
</nav>

scalarHubRockstarHire/app/views/image_links/_form.html.erb
<%= form_with(model: image_link) do |form| %>
    <% if image_link.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(image_link.errors.count, "error") %>:</h2>
  
        <ul>
          <% image_link.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :url, style: "display: block" %>
      <%= form.text_field :url, autocomplete: "off", placeholder: "Enter image link" %>
      
    </div>
  <br>
  
  <div class="field">
      <%= form.label :tag, style: "display: block" %>
      <%= form.text_field :tag_list, placeholder: "Enter tags", autocomplete: "off" %>
    </div><br>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  
  
  
  

scalarHubRockstarHire/app/views/image_links/_image_link.html.erb
<div id="<%= dom_id image_link %>">
  <p>
    <strong>Url:</strong>
    <%= image_link.url %>
  </p>

</div>

scalarHubRockstarHire/app/views/image_links/edit.html.erb
<h1>Editing image link</h1>

<div>
  <% if @image_link.url.present? %>
    <%= image_tag(@image_link.url, alt: "Image", style: "width: 700px;") %><br>
  <% else %>
    <p>No image available.</p>
  <% end %>
</div>

<%= render "form", image_link: @image_link %>

<br>

<div>
  <%= link_to "Show this image link", @image_link %> |
  <%= link_to "Back to image", image_links_path %>
</div>

scalarHubRockstarHire/app/views/image_links/filter.html.erb
<h1>Filtered Images</h1>

<% if @filtered_image_links.nil? || @filtered_image_links.empty? %>
  <p>No images found for the specified tag.</p>
<% else %>
  <ul>
    <% @filtered_image_links.each do |image_link| %>
      <li><%= image_link.title %></li>
    <% end %>
  </ul>
<% end %>

scalarHubRockstarHire/app/views/image_links/index.html.erb
<br>
  <div class="row">
    <% @image_links.each do |image_link| %>
      <div class="col-md-4">
        <% if image_link.url.present? %>
          <%= link_to image_tag(image_link.url, alt: "Image", style: "width: 430px; height: 300px;"), image_link %></br>
        <% else %>
          <p>No image available.</p>
        <% end %></br>
      </div>
    <% end %>
  </div>

scalarHubRockstarHire/app/views/image_links/new.html.erb
  
<div>
<%= render "form", image_link: @image_link %>

<br>
<div>
  <%= link_to "Back to image", image_links_path, class: "badge text-bg-info" %>
</div>
</div>

scalarHubRockstarHire/app/views/image_links/search.html.erb
<h2>Search Results for Tag: <%= @tag %></h2>
<div id="image_links">
<% if @search_results.present? %>
  
    <% @search_results.each do |image_link| %>

   
   <%= link_to image_tag(image_link.url, alt: "Image", style: "width: 430px; height: 300px;"), image_link %>
           
   <% end %>
  
<% else %>
  <p>No results found for tag: <%= @tag %></p>
<% end %>
</div>

scalarHubRockstarHire/app/views/image_links/show.html.erb
</br>
  <ul>
    <div>
      <% if @image_link.url.present? %>
        <%= image_tag(@image_link.url, alt: "Image", style: "width: 700px;") %><br>
      <% else %>
        <p>No image available.</p>
      <% end %>
    </div>
  
</br>
    <div>

      <p><strong>Tags:</strong> </br><%= @image_link.tags.map(&:name).join(', ') %></p>
      <%= link_to "Edit this Image link", edit_image_link_path(@image_link), class: "badge text-bg-info" %> |
      <%= link_to "Show All Image", image_links_path, class: "badge text-bg-info" %>
      
    </br>
  </br>
    <%= button_to "Delete Image", @image_link, method: :delete, data: { confirm: "Are you sure you want to delete this image link?" }, class: "badge text-bg-info" %>
    
  </div>
  </ul>
<h2>Related Images:</h2>
  <ul>
    <% @image_link.tag_list.each do |tag| %>
        <h3><% tag %></h3>
       
        <div id="image_links" class="row">
          <% ImageLink.tagged_with(tag).each do |image| %>
            <div class="col-md-4"> 
            
            <%= link_to image_tag(image.url, class: "img-fluid img-thumbnail zoomable-image", style: "width: 430px; height:300px;"), image_link_path(image) %></br>
            </div>
          <% end %></br>
        </div>
        
    <% end %>
  </ul>
</div>

scalarHubRockstarHire/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScalarHubRockstarHire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="background-color: #ffb3ff;">
    <div>
      <%= render 'home/header' %>
      
    </div>
        
      <%= yield %>

      <%= render 'home/footer' %>
  </body>
</html>